### ISSUE TITLE
splinter.exceptions email

### ISSUE THREAD

**Issue by rienix** [jansenicus/www-coursera-downloader#12]
After running "python www-coursera-downloader.pyc" I get this error:

Getting courses list...
Traceback (most recent call last):
  File "www-coursera-downloader.py", line 744, in <module>
    arrLessonURL, arrLessonTitle = readCSV(strNamaFile)
  File "www-coursera-downloader.py", line 733, in main
    except:
  File "www-coursera-downloader.py", line 192, in getCourses
    print "Using Chrome Web Driver...\n"
  File "/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/__init__.py", line 413, in fill
    field = self.find_by_name(name).first
  File "/usr/local/lib/python2.7/dist-packages/splinter/element_list.py", line 53, in first
    return self[0]
  File "/usr/local/lib/python2.7/dist-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "email"

Any ideas how to solve the problem? The dependencies should be fine ...
Maybe someone had had the same issue and can give me a hint.
Thanx in advance

**Comment by dpdrmj** [comment]
i'm getting the same error.

**Comment by tg-m** [comment]
So there are three of us. :-1:

**Comment by anandjbangad** [comment]
I am getting the same error

**Comment by sinarz** [comment]
I'm facing this error too.
I don't know whats wrong the name of email field is  'email'

**Comment by maiatec** [comment]
I am getting the same error

**Comment by crisoberillo** [comment]
Same here

**Comment by keshore** [comment]
Same Error here. can someone fix it pls..

**Comment by hermamitr** [comment]
Maybe its because coursera changes html content dynamically. one time it works, next time doesnt.

**Comment by Randysirzechs** [comment]
Same error

**Comment by favoyang** [comment]
me too.

**Comment by ProsperaTeam** [comment]
Anyone found the fix for this issue yet? Getting the same error.

**Comment by gyolucio** [comment]
same error

**Comment by naxq0** [comment]
I was getting that error, but then I logged out of coursera on my browser, tried it again a couple times and it ended up working.

However it says that I have no courses available so I didn't get very far

**Comment by abalter** [comment]
Yup. Same here.

**Comment by AnubhavJain1** [comment]
Same error! :/

**Comment by DillipKS** [comment]
Same error. The author is requested to pls solve this issue.

**Comment by enamcse** [comment]
add me in the list

**Comment by blaisb** [comment]
Same here...

**Comment by NAbdulla1** [comment]
I am getting too.
