### ISSUE TITLE
Selenium Issue

### ISSUE THREAD

**Issue by arshpreetsingh** [jansenicus/www-coursera-downloader#22]
I am getting following error while downloading courses: 
Getting courses list...
Traceback (most recent call last):
  File "www-coursera-downloader.py", line 751, in <module>
    main()
  File "www-coursera-downloader.py", line 740, in main
    fullCourseName = getCourses(email, password)
  File "www-coursera-downloader.py", line 202, in getCourses
    browser.fill('email', email)
  File "/home/metal-machine/www-coursera-downloader/mypy/local/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py", line 415, in fill
    field = self.find_by_name(name).first
  File "/home/metal-machine/www-coursera-downloader/mypy/local/lib/python2.7/site-packages/splinter/element_list.py", line 53, in first
    return self[0]
  File "/home/metal-machine/www-coursera-downloader/mypy/local/lib/python2.7/site-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "email"

**Comment by zaverichintanglib** [comment]
Any solution to this ?

**Comment by arshpreetsingh** [comment]
@zaverichintanglib  use this one: https://github.com/coursera-dl/coursera-dl
