### ISSUE TITLE
Error Every Single time I run the File

### ISSUE THREAD

**Issue by skatedude007** [jansenicus/www-coursera-downloader#6]
User and password has been saved to coursera.pass file.
Please delete the file if you want to change your credentials.

Traceback (most recent call last):
  File "www-coursera-downloader.py", line 748, in <module>
    main()
  File "www-coursera-downloader.py", line 734, in main
    email, password = getUserPass("coursera.pass")
  File "www-coursera-downloader.py", line 154, in getUserPass
    decryptedText = decrypt(strText, key1, key2)
  File "www-coursera-downloader.py", line 116, in decrypt
    decryptedText = obj2.decrypt(strInput)
  File "C:\Users\Jash\Miniconda2\lib\site-packages\Crypto\Cipher\blockalgo.py",
line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length

**Comment by skatedude007** [comment]
It is a Windows based PC running miniconda2
